eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/user_service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: user_service_db_password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9094


    # Tüketici (Consumer) Ayarları (Borrow Service olaylarını dinler)
    consumer:
      group-id: user-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false

      properties:
        # 2. Tip bilgisinin başlıkta olduğunu belirt (Header Deserialization)
        spring.json.use.type.headers: true

        # 3. Tip bilgisinin bulunduğu başlık adı (Varsayılan __TypeId__, ancak açıkça belirtmek güvenlidir)
        spring.json.type.header: __TypeId__

        # 4. Güvenilir paket listesi
        spring.json.trusted.packages: "com.turkcell.common.events, com.turkcell.*" # Genellikle joker karakter kullanılır




  # ÖZEL KAFKA TOPIC İSİMLERİ (user-service'in dinlediği topic'ler)
  # Consumer'ların dinleyeceği topic'ler burada açıkça tanımlanmalıdır.
kafka:
  topics:
    fine-events: fine-events

